### ISSUE TITLE
The python package includes the `tests` directory

### ISSUE THREAD

**Issue by xylar** [dengwirda/jigsaw-python#10]
Because of the line:
https://github.com/dengwirda/jigsaw-python/blob/b6e455c22696568f90a7428a49e03c980892c923/setup.py#L135
the `tests` directory is being included in the conda-forge (and presumably the pypi) package.  This directory should be excluded, or better yet only `jigsawpy` should be included:
```
packages=find_packages(include=['jigsawypy', 'jigsawpy.*'])
```

**Comment by dengwirda** [comment]
No worries --- is there a particular issue having the examples included too, or is this to reduce bloat?

**Comment by xylar** [comment]
Yes, anything that's not in the `jigsawpy` directory will collide with other packages that are making the same mistake.  That's how I noticed.

**Comment by xylar** [comment]
It all gets installed in `lib/python3.x/site-packages/<package>` so `lib/python3.x/site-packages/tests` and `lib/python3.x/site-packages/examples`, which is a problem.

**Comment by dengwirda** [comment]
@xylar, would you mind checking whether #11 has resolved this? 
I didn't have luck with `find_packages(include=['jigsawypy', 'jigsawpy.*'])`, but `find_packages(exclude=["tests",])` seems to work okay for me.

**Comment by xylar** [comment]
Yep, it looks good.  I did a test build and the `tests` directory is no longer being included in the package.  There is nothing outside of the expected `jigsawpy` and `jigsawpy-0.3.6.dist-info`.
