### ISSUE TITLE
Still getting output to the terminal with `opts.verbosity = -1`

### ISSUE THREAD

**Issue by xylar** [dengwirda/jigsaw-python#14]
I was told that `opts.verbosity = -1` should mean that no output went to the terminal window, just to the log file.  But I am finding that I still get terminal output when I have this option set.  I verified that the `.jig` file does, indeed have:
```
  VERBOSITY=-1
```
but I still see something like this to the terminal:
```
#------------------------------------------------------------
#
#   ,o, ,o,       /                                 
#    `   `  e88~88e  d88~\   /~~~8e Y88b    e    / 
#   888 888 88   88 C888         88b Y88b  d8b  /   
#   888 888 "8b_d8"  Y88b   e88~-888  Y888/Y88b/  
#   888 888  /        888D C88   888   Y8/  Y8/     
#   88P 888 Cb      \_88P   "8b_-888    Y    Y    
# \_8"       Y8""8D                             
#
#------------------------------------------------------------
# JIGSAW: an unstructured mesh generation library.  
#------------------------------------------------------------
...
```

**Comment by dengwirda** [comment]
Thanks @xylar, I agree this could be improved. 
The intention with `verbosity < 0` is to be a quiet(er) mode, though it seems not quiet enough.
The issue is that the cmd-line jigsaw binaries print the banner before reading the config. file, and hence don't know to be quiet yet --- I've tagged this to be improved for `0.9.15.xx`.

**Comment by xylar** [comment]
@dengwirda, that sounds good.  I think this is clear but just to be sure: For our purposes, we would still want the output at some verbosity (`verbosity = 1`?) to the log file even if nothing is written to the terminal.

**Comment by dengwirda** [comment]
Via the `1.0.0.x` updates in #17, `opts.verbosity <= -2` should print nothing to stdout, though will still create a `*.log` file. There's also now a 'logarithmic' output scheme implemented, which should be quieter in general.
Reducing the stdout verbosity will reduce the log-file verbosity too though.
